version: 2.1

orbs:
  github-release: duffn/github-release@dev:alpha

jobs:
  release:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - github-release/release

workflows:
  release:
    jobs:
      - release:
          filters:
            branches:
              only:
                - main
