version: 2.1

orbs:
  github-release: duffn/github-release@dev:alpha

jobs:
  release:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
          fingerprints:
            - "f2:32:19:9f:e7:a4:73:65:1a:0c:6c:70:58:61:e3:05"
      - checkout
      - github-release/release:
          bump: minor

workflows:
  release:
    jobs:
      - release
